import { config } from "dotenv";
config({ path: ".env.local" });

import { db } from "@/lib/db";
import { bookings } from "@/lib/schema";
import { eq, and, gte, lte } from "drizzle-orm";

// Manual April booking updates from Excel
const aprilUpdates = [
  {
    guestName: "Philip LIuction",
    unit: "1118",
    totalFee: 1200,
    dpAmount: 500,
    dpReceivedBy: "SR JAMES",
    fpAmount: 1000,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Cristine Lode",
    unit: "1558",
    totalFee: 1500,
    dpAmount: 500,
    dpReceivedBy: "SR JAMES",
    fpAmount: 1000,
    fpReceivedBy: "no mike",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Sharmeine Nestor",
    unit: "1245",
    totalFee: 1300,
    dpAmount: 500,
    dpReceivedBy: "SR JAMES",
    fpAmount: 800,
    fpReceivedBy: "no mike",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Sharlene Salise Basso",
    unit: "1118",
    totalFee: 1500,
    dpAmount: 500,
    dpReceivedBy: "SR JAMES",
    fpAmount: 1000,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Chelsay Lasales",
    unit: "1245",
    totalFee: 1600,
    dpAmount: 700,
    dpReceivedBy: "SR JAMES",
    fpAmount: 900,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Maria Cristine Fuentes",
    unit: "1118",
    totalFee: 500,
    dpAmount: 0,
    dpReceivedBy: "SR JAMES",
    fpAmount: 500,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Sim Campeon",
    unit: "1558",
    totalFee: 2000,
    dpAmount: 700,
    dpReceivedBy: "SR JAMES",
    fpAmount: 1300,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Nichole Anne Reyes",
    unit: "1245",
    totalFee: 1800,
    dpAmount: 500,
    dpReceivedBy: "SR MIKE",
    fpAmount: 1299,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Aina Tiiasa",
    unit: "1116",
    totalFee: 1400,
    dpAmount: 500,
    dpReceivedBy: "SR JAMES",
    fpAmount: 900,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Maria Cristine Reyes",
    unit: "1245",
    totalFee: 1800,
    dpAmount: 800,
    dpReceivedBy: "SR MIKE",
    fpAmount: 1000,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Axel Mark",
    unit: "1245",
    totalFee: 1300,
    dpAmount: 500,
    dpReceivedBy: "SR MIKE",
    fpAmount: 800,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Arturo Magasang",
    unit: "1116",
    totalFee: 1229,
    dpAmount: 500,
    dpReceivedBy: "SR JAMES",
    fpAmount: 729,
    fpReceivedBy: "no mike",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "James de Jesus",
    unit: "1118",
    totalFee: 1800,
    dpAmount: 500,
    dpReceivedBy: "SR JAMES",
    fpAmount: 800,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Pia Mesialor Repollos",
    unit: "1558",
    totalFee: 1200,
    dpAmount: 400,
    dpReceivedBy: "SR JAMES",
    fpAmount: 800,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Cielo Victolero",
    unit: "1118",
    totalFee: 1300,
    dpAmount: 500,
    dpReceivedBy: "SR JAMES",
    fpAmount: 800,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Seia Santos",
    unit: "1118",
    totalFee: 1229,
    dpAmount: 500,
    dpReceivedBy: "SR JAMES",
    fpAmount: 729,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Seah Antalan",
    unit: "1558",
    totalFee: 1229,
    dpAmount: 0,
    dpReceivedBy: "SR JAMES",
    fpAmount: 1299,
    fpReceivedBy: "SR MIKE",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Aih Joy Elimano",
    unit: "1558",
    totalFee: 1300,
    dpAmount: 0,
    dpReceivedBy: "SR JAMES",
    fpAmount: 1300,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Aiko Larder",
    unit: "1245",
    totalFee: 1300,
    dpAmount: 500,
    dpReceivedBy: "SR MIKE",
    fpAmount: 800,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Trusty Corena",
    unit: "1245",
    totalFee: 1699,
    dpAmount: 0,
    dpReceivedBy: "SR JAMES",
    fpAmount: 1699,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Rochelle Morays",
    unit: "1116",
    totalFee: 1300,
    dpAmount: 500,
    dpReceivedBy: "SR JAMES",
    fpAmount: 800,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Roxanne Smalial",
    unit: "1118",
    totalFee: 1300,
    dpAmount: 500,
    dpReceivedBy: "SR JAMES",
    fpAmount: 800,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Roel Lim",
    unit: "1118",
    totalFee: 1300,
    dpAmount: 500,
    dpReceivedBy: "SR JAMES",
    fpAmount: 800,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Lincol Lephis",
    unit: "1558",
    totalFee: 1299,
    dpAmount: 500,
    dpReceivedBy: "SR JAMES",
    fpAmount: 799,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Almise Acosta",
    unit: "1245",
    totalFee: 1200,
    dpAmount: 0,
    dpReceivedBy: "SR JAMES",
    fpAmount: 1200,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Xen Rupa",
    unit: "1245",
    totalFee: 1200,
    dpAmount: 500,
    dpReceivedBy: "REIMAR",
    fpAmount: 700,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Ivel Lazzaro Camara",
    unit: "1118",
    totalFee: 1200,
    dpAmount: 500,
    dpReceivedBy: "SR JAMES",
    fpAmount: 700,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Bryen Salcazar",
    unit: "1558",
    totalFee: 1110,
    dpAmount: 500,
    dpReceivedBy: "SR JAMES",
    fpAmount: 640,
    fpReceivedBy: "REIMAR",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Onice Pataguan",
    unit: "1118",
    totalFee: 1300,
    dpAmount: 500,
    dpReceivedBy: "SR JAMES",
    fpAmount: 800,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Jerald Junior Lagmay",
    unit: "1245",
    totalFee: 1400,
    dpAmount: 800,
    dpReceivedBy: "SR JAMES",
    fpAmount: 600,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Justine De Jose",
    unit: "1245",
    totalFee: 1500,
    dpAmount: 500,
    dpReceivedBy: "REIMAR",
    fpAmount: 1000,
    fpReceivedBy: "SR MIKE",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Dreyad Duog",
    unit: "1845",
    totalFee: 1300,
    dpAmount: 0,
    dpReceivedBy: "SR JAMES",
    fpAmount: 1300,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Precious Dull",
    unit: "1118",
    totalFee: 1500,
    dpAmount: 500,
    dpReceivedBy: "REIMAR",
    fpAmount: 1000,
    fpReceivedBy: "REIMAR",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Imad Reshaad",
    unit: "1116",
    totalFee: 0,
    dpAmount: 0,
    dpReceivedBy: "SR JAMES",
    fpAmount: 0,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "NINA",
    unit: "1245",
    totalFee: 1000,
    dpAmount: 500,
    dpReceivedBy: "REIMAR",
    fpAmount: 500,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Anyka sa Gamat",
    unit: "1245",
    totalFee: 1000,
    dpAmount: 500,
    dpReceivedBy: "SR JAMES",
    fpAmount: 500,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Ronie Sace",
    unit: "1245",
    totalFee: 1100,
    dpAmount: 0,
    dpReceivedBy: "SR JAMES",
    fpAmount: 1100,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Kevin Gamban",
    unit: "1116",
    totalFee: 1999,
    dpAmount: 350,
    dpReceivedBy: "REIMAR",
    fpAmount: 650,
    fpReceivedBy: "REIMAR",
    remainingBalance: 999,
    paymentStatus: "Partial Payment",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Nicolas Humiahan",
    unit: "1118",
    totalFee: 1500,
    dpAmount: 700,
    dpReceivedBy: "REIMAR",
    fpAmount: 800,
    fpReceivedBy: "REIMAR",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Jasice Earland",
    unit: "1558",
    totalFee: 1299,
    dpAmount: 500,
    dpReceivedBy: "REIMAR",
    fpAmount: 799,
    fpReceivedBy: "REIMAR",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Larso Polly Sanchez",
    unit: "1245",
    totalFee: 1200,
    dpAmount: 300,
    dpReceivedBy: "REIMAR",
    fpAmount: 900,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Joni Jettle Solar",
    unit: "1558",
    totalFee: 1800,
    dpAmount: 500,
    dpReceivedBy: "REIMAR",
    fpAmount: 1300,
    fpReceivedBy: "REIMAR",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Renie Baguso",
    unit: "1118",
    totalFee: 1600,
    dpAmount: 1000,
    dpReceivedBy: "REIMAR",
    fpAmount: 600,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "DP Paid",
  },
  {
    guestName: "Dainee Agina",
    unit: "1245",
    totalFee: 1300,
    dpAmount: 1000,
    dpReceivedBy: "REIMAR",
    fpAmount: 300,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "DP Paid",
  },
  {
    guestName: "Lorraine Garabillo",
    unit: "1245",
    totalFee: 1299,
    dpAmount: 500,
    dpReceivedBy: "REIMAR",
    fpAmount: 0,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 799,
    paymentStatus: "DP Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Serlyn Juliae Balinoan",
    unit: "1116",
    totalFee: 1300,
    dpAmount: 500,
    dpReceivedBy: "SR JAMES",
    fpAmount: 0,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 1100,
    paymentStatus: "DP Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Sebastian Blanca",
    unit: "1245",
    totalFee: 1200,
    dpAmount: 500,
    dpReceivedBy: "REIMAR",
    fpAmount: 0,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 700,
    paymentStatus: "DP Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Dorothy Period",
    unit: "1558",
    totalFee: 1300,
    dpAmount: 0,
    dpReceivedBy: "SR JAMES",
    fpAmount: 0,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 1300,
    paymentStatus: "No DP",
    hasConflict: "1000 Conflict",
  },
  {
    guestName: "Ashiel Jean",
    unit: "1245",
    totalFee: 1900,
    dpAmount: 0,
    dpReceivedBy: "SR JAMES",
    fpAmount: 0,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 1900,
    paymentStatus: "No DP",
    hasConflict: "1900 Conflict",
  },
  {
    guestName: "Bryan Hermichon",
    unit: "1116",
    totalFee: 1799,
    dpAmount: 0,
    dpReceivedBy: "SR JAMES",
    fpAmount: 0,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 1299,
    paymentStatus: "No DP",
    hasConflict: "1299 Conflict",
  },
  {
    guestName: "Mary Morales Rosas",
    unit: "1558",
    totalFee: 1800,
    dpAmount: 1100,
    dpReceivedBy: "SR JAMES",
    fpAmount: 0,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 0,
    paymentStatus: "DP Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Jermy Pen",
    unit: "1118",
    totalFee: 1600,
    dpAmount: 0,
    dpReceivedBy: "REIMAR",
    fpAmount: 0,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 1100,
    paymentStatus: "No DP",
    hasConflict: "1100 Conflict",
  },
  {
    guestName: "Jen Cruz",
    unit: "1558",
    totalFee: 1300,
    dpAmount: 500,
    dpReceivedBy: "REIMAR",
    fpAmount: 0,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 800,
    paymentStatus: "DP Paid",
    hasConflict: "0 Conflict",
  },
  {
    guestName: "Merlin Sa Maj",
    unit: "1558",
    totalFee: 1200,
    dpAmount: 400,
    dpReceivedBy: "SR JAMES",
    fpAmount: 0,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 800,
    paymentStatus: "DP Paid",
    hasConflict: "1100 Conflict",
  },
  {
    guestName: "Aidah Espondaera",
    unit: "1116",
    totalFee: 1899,
    dpAmount: 500,
    dpReceivedBy: "SR JAMES",
    fpAmount: 0,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 1399,
    paymentStatus: "DP Paid",
    hasConflict: "1399 Conflict",
  },
  {
    guestName: "Jaseline Racelan",
    unit: "1558",
    totalFee: 1800,
    dpAmount: 500,
    dpReceivedBy: "SR JAMES",
    fpAmount: 0,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 1300,
    paymentStatus: "DP Paid",
    hasConflict: "1300 Conflict",
  },
  {
    guestName: "Ivan Marugel Fpilno Cham",
    unit: "1845",
    totalFee: 1599,
    dpAmount: 500,
    dpReceivedBy: "REIMAR",
    fpAmount: 0,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 1099,
    paymentStatus: "DP Paid",
    hasConflict: "1099 Conflict",
  },
  {
    guestName: "Prince Arland Dela Cruz",
    unit: "1558",
    totalFee: 1499,
    dpAmount: 0,
    dpReceivedBy: "SR JAMES",
    fpAmount: 0,
    fpReceivedBy: "SR JAMES",
    remainingBalance: 999,
    paymentStatus: "No DP",
    hasConflict: "999 Conflict",
  },
  {
    guestName: "Billy Glen",
    unit: "1558",
    totalFee: 1299,
    dpAmount: 0,
    dpReceivedBy: "REIMAR",
    fpAmount: 1299,
    fpReceivedBy: "Reimar",
    remainingBalance: 0,
    paymentStatus: "Fully Paid",
    hasConflict: "0 Conflict",
  },
];

async function updateAprilBookings() {
  try {
    console.log(`Starting update of ${aprilUpdates.length} April bookings...`);

    for (const update of aprilUpdates) {
      // Find booking by guest name (all April bookings)
      const result = await db
        .update(bookings)
        .set({
          totalFee: update.totalFee,
          dpAmount: update.dpAmount,
          dpReceivedBy: update.dpReceivedBy,
          fpAmount: update.fpAmount,
          fpReceivedBy: update.fpReceivedBy,
          remainingBalance: update.remainingBalance,
          paymentStatus: update.paymentStatus,
          hasConflict: update.hasConflict,
          updatedAt: new Date(),
        })
        .where(
          and(
            eq(bookings.guestName, update.guestName),
            eq(bookings.unit, update.unit)
          )
        );

      console.log(`✓ Updated: ${update.guestName} (Unit ${update.unit})`);
    }

    console.log("\n✅ All April bookings updated successfully!");
  } catch (error) {
    console.error("❌ Error updating bookings:", error);
    process.exit(1);
  }
}

updateAprilBookings();
